services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: billpay-backend
    network_mode: "host"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_PUBLIC_JDBC_URL: jdbc:postgresql://127.0.0.1:5432/billpay
      SPRING_DATASOURCE_PUBLIC_USERNAME: billpay
      SPRING_DATASOURCE_PUBLIC_PASSWORD: ${DB_PASSWORD}
      SPRING_DATASOURCE_TENANT_TEMPLATE_URL: jdbc:postgresql://127.0.0.1:5432/billpay
      SPRING_DATASOURCE_TENANT_TEMPLATE_USERNAME: billpay
      SPRING_DATASOURCE_TENANT_TEMPLATE_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      WEBHOOK_BASE_URL: https://bnp.cardbin.net/api
      JAVA_OPTS: -Xmx1g -Xms512m
      TZ: Asia/Seoul
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production
      args:
        VITE_API_BASE_URL: https://bnp.cardbin.net/api
    container_name: billpay-frontend
    ports:
      - "3010:80"
    environment:
      TZ: Asia/Seoul
    restart: unless-stopped
